Language: python

python: 3.8.1

install:
  - pip install requirements.txt

script:
  - python test.py

addons:
  ssh_known_hosts: moon.scs.ryerson.ca
  
before_install:
  - openssl aes-256-cbc -K $encrypted_8809f85d1f7a_key -iv $encrypted_8809f85d1f7a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  
deploy:
  provider: scripts
  skip_cleanup: true
  script: rsync -r --delete-after --quiet ${TRAVIS_BUILD_DIR}/dat ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/avm/courses/cps847/${DEPLOY_USER}
  on:
    branch: master